server {
    listen       80;
    server_name  localhost;

    root /usr/share/nginx/html;  # 确保根目录正确
    index index.html index.htm;  # 确保 index 指令正确设置

    location / {
         if ($request_filename ~ .*.(html|htm)$) {
          expires -1s;
        }
        if ($request_filename ~ .*.(js|css|jpe?g|png|gif)$) {
          expires 30d;
        }
        try_files $uri $uri/ =404;  # 确保正确处理目录请求
    }
}
